### ISSUE TITLE
esc login not working

### ISSUE THREAD

**Issue by toriancrane** [pulumi/esc#100]
### What happened?

When I try to run the `esc login` command, it returns an error:

```
$ esc login
Error: not currently logged in
```

### Example

Just try and run the `esc login` command

### Output of `pulumi about`

```bash
CLI          
Version      3.88.0
Go Version   go1.21.1
Go Compiler  gc

Plugins
NAME          VERSION
azure         5.52.0
azure-native  2.11.0
azuread       5.42.0
python        unknown

Host     
OS       amazon
Version  2
Arch     x86_64

This project is written in python: executable='/home/ec2-user/environment/azure-oidc/venv/bin/python3' version='3.7.16'

Current Stack: v-torian-pulumi-corp/azure-oidc/dev

TYPE                                                                                         URN
pulumi:pulumi:Stack                                                                          urn:pulumi:dev::azure-oidc::pulumi:pulumi:Stack::azure-oidc-dev
pulumi:providers:azure-native                                                                urn:pulumi:dev::azure-oidc::pulumi:providers:azure-native::default
pulumi:providers:azuread                                                                     urn:pulumi:dev::azure-oidc::pulumi:providers:azuread::default_5_42_0
pulumi:providers:azure-native                                                                urn:pulumi:dev::azure-oidc::pulumi:providers:azure-native::default_2_11_0
azure-native:resources:ResourceGroup                                                         urn:pulumi:dev::azure-oidc::azure-native:resources:ResourceGroup::resourceGroup
azuread:index/application:Application                                                        urn:pulumi:dev::azure-oidc::azuread:index/application:Application::oidc-app-registration
azuread:index/applicationFederatedIdentityCredential:ApplicationFederatedIdentityCredential  urn:pulumi:dev::azure-oidc::azuread:index/applicationFederatedIdentityCredential:ApplicationFederatedIdentityCredential::federatedIdentityCredential


Found no pending operations associated with dev

Backend        
Name           pulumi.com
URL            https://app.pulumi.com/v-torian-pulumi-corp
User           v-torian-pulumi-corp
Organizations  v-torian-pulumi-corp, zephyr, pulumi
Token type     personal

Dependencies:
NAME                 VERSION
pip                  23.2.1
pulumi-azure         5.52.0
pulumi-azure-native  2.11.0
pulumi-azuread       5.42.0
setuptools           68.0.0
wheel                0.41.2

Pulumi locates its logs in /tmp by default
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by cnunciato** [comment]
I believe the expected behavior here is that like `pulumi login`, in the absence of an `api.pulumi.com` token, the CLI prompts with the magic login flow:

```
$ pulumi login
Manage your Pulumi stacks by logging in.
Run `pulumi --help` for alternative login options.
Enter your access token from https://app.pulumi.com/account/tokens
    or hit <ENTER> to log in using your browser                   :
```

Currently, `esc login` doesn't do this (it just fails as described) -- although passing `https://api.pulumi.com` does seem to work:

```
$ esc login https://api.pulumi.com
Manage your Pulumi ESC environments by logging in.
Run `esc --help` for alternative login options.
Enter your access token from https://app.pulumi.com/account/tokens
    or hit <ENTER> to log in using your browser                   :
```

**Comment by cnunciato** [comment]
I don't think this is quite fixed yet. I just downloaded and installed 0.5.3, and here's the behavior I see now (starting with nothing at `~/.pulumi`):

```
$ esc login
Manage your Pulumi ESC environments by logging in.
Run `esc --help` for alternative login options.
Enter your access token from https://app.pulumi.com/account/tokens
    or hit <ENTER> to log in using your browser                   :
We've launched your web browser to complete the login process.

Waiting for login to complete...
Logged in to pulumi.com as cnunciato (https://app.pulumi.com/cnunciato)

$ esc env ls
Error: no credentials. Please run `esc login` to log in.

$ esc login
Logged in to pulumi.com as cnunciato (https://app.pulumi.com/cnunciato)

$ esc env ls
Error: no credentials. Please run `esc login` to log in.

$ esc login https://api.pulumi.com
Logged in to pulumi.com as cnunciato (https://app.pulumi.com/cnunciato)

$ esc env ls
infra-personal
test
...

$ esc logout
================================================================================
The esc CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/esc/issues/
Please provide all of the below text in your report.
================================================================================
esc Version:      v0.5.3
Go Version:       go1.20.8
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.20.8/x64/src/runtime/debug/stack.go:24 +0x64
main.panicHandler()
	/Users/runner/work/esc/esc/cmd/esc/main.go:23 +0x34
panic({0x106144100, 0x1074d7860})
	/Users/runner/hostedtoolcache/go/1.20.8/x64/src/runtime/panic.go:884 +0x204
github.com/pulumi/esc/cmd/esc/cli.newLogoutCmd.func1(0x140016c4f00?, {0x107556d88?, 0x0?, 0x0?})
	/Users/runner/work/esc/esc/cmd/esc/cli/logout.go:50 +0x110
github.com/spf13/cobra.(*Command).execute(0x140016c4f00, {0x107556d88, 0x0, 0x0})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x14001466c00)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(0x1400010c000?)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main.func1()
	/Users/runner/work/esc/esc/cmd/esc/main.go:43 +0x44
main.main()
	/Users/runner/work/esc/esc/cmd/esc/main.go:44 +0x1c
```
 
So it looks like `login` is now opening the browser and capturing a token, but not immediately recognizing it until I run `esc login https://api.pulumi.com` as before.
