### ISSUE TITLE
Setting a value to `""` causes a panic

### ISSUE THREAD

**Issue by cnunciato** [pulumi/esc#109]
```
$ esc env set test somekey ""

================================================================================
The esc CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/esc/issues/
Please provide all of the below text in your report.
================================================================================
esc Version:      v0.5.2
Go Version:       go1.20.8
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            runtime error: index out of range [0] with length 0

goroutine 1 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.20.8/x64/src/runtime/debug/stack.go:24 +0x64
main.panicHandler()
	/Users/runner/work/esc/esc/cmd/esc/main.go:23 +0x34
panic({0x102d61be0, 0x14000235cb0})
	/Users/runner/hostedtoolcache/go/1.20.8/x64/src/runtime/panic.go:884 +0x204
github.com/pulumi/esc/cmd/esc/cli.newEnvSetCmd.func1(0x14001323500?, {0x140005a29c0, 0x3, 0x3})
	/Users/runner/work/esc/esc/cmd/esc/cli/env_set.go:59 +0x968
github.com/spf13/cobra.(*Command).execute(0x14001323500, {0x140005a2930, 0x3, 0x3})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x14000015800)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(0x1400010c000?)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main.func1()
	/Users/runner/work/esc/esc/cmd/esc/main.go:43 +0x44
main.main()
	/Users/runner/work/esc/esc/cmd/esc/main.go:44 +0x1c
```

**Comment by pierskarsenbarg** [comment]
This looks to be very similar to https://github.com/pulumi/pulumi/issues/14146
