### ISSUE TITLE
panic opening an environment for different backend

### ISSUE THREAD

**Issue by lblackstone** [pulumi/esc#162]
### What happened?

I got the following panic when trying to open an environment for a different backend than the one I was currently logged into:

```
esc env open stacks
================================================================================
The esc CLI encountered a fatal error. This is a bug!
We would appreciate a report: https://github.com/pulumi/esc/issues/
Please provide all of the below text in your report.
================================================================================
esc Version:      v0.5.7
Go Version:       go1.20.8
Go Compiler:      gc
Architecture:     arm64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
	/Users/runner/hostedtoolcache/go/1.20.8/x64/src/runtime/debug/stack.go:24 +0x64
main.panicHandler()
	/Users/runner/work/esc/esc/cmd/esc/main.go:23 +0x34
panic({0x10635c120, 0x1076f3980})
	/Users/runner/hostedtoolcache/go/1.20.8/x64/src/runtime/panic.go:884 +0x204
github.com/pulumi/esc/cmd/esc/cli.(*escCommand).getCachedCredentials(0x14000000f00, {0x10668e100?, 0x14000126018?}, {0x1400155b3a0, 0x1f}, 0x0?)
	/Users/runner/work/esc/esc/cmd/esc/cli/login.go:185 +0x58
github.com/pulumi/esc/cmd/esc/cli.(*escCommand).getCachedClient(0x14000000f00, {0x10668e100, 0x14000126018})
	/Users/runner/work/esc/esc/cmd/esc/cli/login.go:167 +0xb0
github.com/pulumi/esc/cmd/esc/cli.newEnvOpenCmd.func1(0x1400093e600?, {0x140010be370, 0x1, 0x1})
	/Users/runner/work/esc/esc/cmd/esc/cli/env_open.go:38 +0x6c
github.com/spf13/cobra.(*Command).execute(0x1400093e600, {0x140010be280, 0x1, 0x1})
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x5c8
github.com/spf13/cobra.(*Command).ExecuteC(0x140010b2000)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x35c
github.com/spf13/cobra.(*Command).Execute(0x1400010c000?)
	/Users/runner/go/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992 +0x1c
main.main.func1()
	/Users/runner/work/esc/esc/cmd/esc/main.go:43 +0x44
main.main()
	/Users/runner/work/esc/esc/cmd/esc/main.go:44 +0x1c

```

### Example

1. pulumi login to the default cloud service
2. esc login to a devstack cloud service
3. pulumi logout && pulumi login to the devstack cloud service
4. pulumi logout and pulumi login to the default cloud service
5. esc env open <stack> causes a panic

### Output of `pulumi about`

```
esc version
v0.5.7
```

### Additional context

This may not be specific to opening an environment. I suspect it may be a bug with logging in and out of different backends between `pulumi` and `esc`.

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by komalali** [comment]
I could not repro this panic. The last `esc env ls` results in `Error: could not determine current cloud: account 'https://api.komal.pulumi-dev.io' not found.Please re-run `esc login` to reset your credentials file.` and I had to rerun `esc login https://api.komal.pulumi-dev.io` to continue.
