### ISSUE TITLE
Panic when listing environments when not logged in

### ISSUE THREAD

**Issue by pierskarsenbarg** [pulumi/esc#89]
### What happened?

When not logged in (so no `credentials.json` file, ran 'pulumi env ls'. Got the following:

```
Pulumi Version:   v3.88.0
Go Version:       go1.21.2
Go Compiler:      gc
Architecture:     amd64
Operating System: darwin
Panic:            runtime error: invalid memory address or nil pointer dereference

goroutine 1 [running]:
runtime/debug.Stack()
        /usr/local/Cellar/go/1.21.2/libexec/src/runtime/debug/stack.go:24 +0x5e
main.panicHandler(0xc001cbff07)
        /private/tmp/pulumi-20231010-4719-17hymnh/pkg/cmd/pulumi/main.go:35 +0x45
panic({0x102265ae0?, 0x104427f60?})
        /usr/local/Cellar/go/1.21.2/libexec/src/runtime/panic.go:914 +0x21f
github.com/pulumi/esc/cmd/esc/cli.(*escCommand).getCachedClient(0xc000a66dc0, {0x102e97910, 0x1044aebc0})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/esc@v0.4.0/cmd/esc/cli/login.go:150 +0x76
github.com/pulumi/esc/cmd/esc/cli.newEnvLsCmd.func1(0xc00146de00?, {0x1044aebc0?, 0x0?, 0x0?})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/pulumi/esc@v0.4.0/cmd/esc/cli/env_ls.go:29 +0x4b
github.com/spf13/cobra.(*Command).execute(0xc001466300, {0x1044aebc0, 0x0, 0x0})
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:940 +0x87c
github.com/spf13/cobra.(*Command).ExecuteC(0xc001ea6f00)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3a5
github.com/spf13/cobra.(*Command).Execute(...)
        /Users/brew/Library/Caches/Homebrew/go_mod_cache/pkg/mod/github.com/spf13/cobra@v1.7.0/command.go:992
main.main()
        /private/tmp/pulumi-20231010-4719-17hymnh/pkg/cmd/pulumi/main.go:56 +0x58
```

### Example

n/a

### Output of `pulumi about`

```
CLI          
Version      3.88.0
Go Version   go1.21.2
Go Compiler  gc

Plugins
NAME    VERSION
aws     5.42.0
awsx    1.0.5
docker  3.6.1
nodejs  unknown

Host     
OS       darwin
Version  14.0
Arch     x86_64

This project is written in nodejs: executable='/Users/piers/.nvm/versions/node/v18.12.1/bin/node' version='v18.12.1'

Backend        
Name           pulumi.com
URL            https://app.pulumi.com
User           Unknown
Organizations  
Token type     personal

Dependencies:
NAME            VERSION
@pulumi/pulumi  3.87.0
@types/node     16.18.58
@pulumi/aws     5.42.0
@pulumi/awsx    1.0.5

Pulumi locates its logs in /var/folders/69/3w1gr05s2pq36wn49bhyknym0000gn/T/ by default
warning: Failed to get information about the current stack: No current stack
```

### Contributing

Vote on this issue by adding a 👍 reaction. 
To contribute a fix for this issue, leave a comment (and link to your pull request, if you've opened one already).

**Comment by lblackstone** [comment]
https://github.com/pulumi/esc/blob/7e8c12ad30f80c4e6604e525233d97c1bd2497f8/cmd/esc/cli/workspace/credentials.go#L83 is the culprit. This is returning a `nil` `*Account`, and then dereferencing it without a `nil` check in https://github.com/pulumi/esc/blob/7e8c12ad30f80c4e6604e525233d97c1bd2497f8/cmd/esc/cli/login.go#L150
